services:
  fizzbuzz.api:
    image: fizzbuzz.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: FizzBuzz.Api/Dockerfile
    restart: on-failure  
    depends_on:
      - postgres-db
    networks:
      - frontend

  postgres-db:
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user_metrics
      - POSTGRES_PASSWORD=lbc2026!
      - POSTGRES_DB=metrics_db
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    networks:
      - frontend

networks:
  frontend:
volumes:
  database-data: